name: image_picker_widget
description: "A image picker widget that duplicate tailwind file upload behavior"
version: 0.0.1
homepage: https://iransign-web.pages.dev/

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  image_picker: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: